name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.WEBSCICLE_SSH_PRIVATE_KEY }}
          script: |
            # Set up Git credentials for the token
            git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "https://github.com/"

            cd ~/demonandibackend
            git pull origin main
            sudo cp -rf * /var/www/demoapinandi.webscicle.com
            cd /var/www/demoapinandi.webscicle.com
            sudo docker-compose down
            sudo docker-compose up --build -d
